# Generated by Django 5.0 on 2024-03-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0024_journalrecievedidmodel_user'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, max_length=220, null=True)),
                ('trans_sub_type', models.CharField(blank=True, max_length=220, null=True)),
                ('bill_address', models.CharField(blank=True, max_length=220, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=220, null=True)),
                ('reference_no', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=220, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('transportation', models.CharField(blank=True, max_length=220, null=True)),
                ('kilometers', models.CharField(blank=True, max_length=220, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='file/')),
                ('sub_total', models.IntegerField(blank=True, default=0, null=True)),
                ('CGST', models.IntegerField(blank=True, default=0, null=True)),
                ('SGST', models.IntegerField(blank=True, default=0, null=True)),
                ('IGST', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('adjustment', models.IntegerField(blank=True, default=0, null=True)),
                ('grand_total', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Eway_bill_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, max_length=220, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('eway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.eway')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Eway_bill_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=220, null=True)),
                ('hsn', models.CharField(blank=True, max_length=220, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('tax_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('eway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.eway')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Eway_bill_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
