# Generated by Django 5.0 on 2024-04-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0027_eway_bill_transportation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='eway',
            name='hsnno',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='eway',
            name='sacno',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
